variables:
    VERSION: "v1.0.1"
before_script:
    - echo "Begin"
    - /gaodun/dist/python2.7/bin/pip2.7 install oss2
    - /gaodun/dist/python2.7/bin/pip2.7 install simplejson
    - mkdir -p /gaodun/tmp/gitlab_tar_file/
maketar:
  script:
    - export ITEM_NAME=`basename $CI_PROJECT_DIR`
    - cd `dirname $CI_PROJECT_DIR`
    - echo '代码总行数:'`find ./$ITEM_NAME -type f -regextype posix-extended -regex '.*\.(php|py|go|css|js|html|htm)'|xargs cat|wc -l`
    - git init
    - echo "itemname|$ITEM_NAME" > "$ITEM_NAME.txt"
    - echo "ci_build_ref|$CI_BUILD_REF" >> "$ITEM_NAME.txt"
    - echo "ci_build_tag|$CI_BUILD_TAG" >> "$ITEM_NAME.txt"
    - echo "ci_build_name|$CI_BUILD_NAME" >> "$ITEM_NAME.txt"
    - echo "ci_build_stage|$CI_BUILD_STAGE" >> "$ITEM_NAME.txt"
    - echo "ci_build_ref_name|$CI_BUILD_REF_NAME" >> "$ITEM_NAME.txt"
    - echo "ci_build_repo|$CI_BUILD_REPO" >> "$ITEM_NAME.txt"
    - echo "ci_build_id|$CI_BUILD_ID" >> "$ITEM_NAME.txt"
    - echo "ci_project_id|$CI_PROJECT_ID" >> "$ITEM_NAME.txt"
    - echo "ci_project_dir|$CI_PROJECT_DIR" >> "$ITEM_NAME.txt"
    - cp -f "$ITEM_NAME.txt" "$CI_PROJECT_DIR/DEPLOY"
    - cp -f "$ITEM_NAME.txt" "$CI_PROJECT_DIR/status.js"
    - rm -rf "$ITEM_NAME"/src
    - tar czf "$ITEM_NAME-${CI_BUILD_REF_NAME/\//_}-$CI_BUILD_REF.tar.gz" "$ITEM_NAME" "$ITEM_NAME.txt"
    - mv "$ITEM_NAME-${CI_BUILD_REF_NAME/\//_}-$CI_BUILD_REF.tar.gz" /gaodun/tmp/gitlab_tar_file/
    - export itemfile=`dirname $CI_PROJECT_DIR`"/"$ITEM_NAME".txt"
    - export localfile="/gaodun/tmp/gitlab_tar_file/$ITEM_NAME-${CI_BUILD_REF_NAME/\//_}-$CI_BUILD_REF.tar.gz"
    - /gaodun/dist/python2.7/bin/python2.7 /gaodun/dist/script/oss/oss_upload.py $localfile $itemfile
    - rm -f "/gaodun/tmp/gitlab_tar_file/$ITEM_NAME-${CI_BUILD_REF_NAME/\//_}-$CI_BUILD_REF.tar.gz"
    - rm -f "$ITEM_NAME.txt"
    
after_script:
    - echo "End"